version: '3'

services:
  spring-app:
    image: vvvv4449/deploy
    ports:
      - "8090:8080"
    env_file: .env
    networks:
      - net-deploy
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - net-deploy
networks:
  net-deploy: