name: deploy

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot application
        run: ./gradlew build -x test

